.eslintignore
.github/workflows/pr_workflow.yaml
.prettierrc.js
frontend/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.test.tsx
frontend/src/App.tsx
frontend/src/index.css
frontend/src/index.tsx
frontend/src/react-app-env.d.ts
frontend/src/setupTests.ts
frontend/tsconfig.json

fe-feat/init

---

.eslintignore
.github/workflows/pr_workflow.yaml
.prettierrc.js
frontend/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.test.tsx
frontend/src/App.tsx
frontend/src/index.css
frontend/src/index.tsx
frontend/src/react-app-env.d.ts
frontend/src/setupTests.ts
frontend/tsconfig.json

DEPLOY : FE-초기 환경 세팅

---

.eslintignore
.github/workflows/pr_workflow.yaml
.prettierrc.js
frontend/.gitignore
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.test.tsx
frontend/src/App.tsx
frontend/src/api/getQuery.tsx
frontend/src/components/taskInputComponents.tsx
frontend/src/index.css
frontend/src/index.tsx
frontend/src/pages/consolePage.tsx
frontend/src/pages/registerCodePage.tsx
frontend/src/react-app-env.d.ts
frontend/src/setupTests.ts
frontend/tsconfig.json

DEPLOY : FE - 초기 환경 세팅

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/config/WebClientConfig.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/TaskController.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/DatabaseService.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/MongoDBServiceImpl.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskSerivce.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskServiceStreamImpl.java

<br/>
<br/>
- 이후의 연계되는 서비스에 대해 어떻게 처리할지 고민되는 상태에서 추가적인 서비스를 구성한다면 바로 적용할 수 있도록 준비해두었다. 
<br/>
- #close JIRA-91
- #close JIRA-37

be-feat/userAddCode

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/TaskController.java

<br/>
<br/>
- 없음
<br/>
- #close JIRA-113

be-feat/apiMethodChange

---

frontend/package-lock.json

<br/>
- ConsolePage와 CodeInputPage를 main에 merge 할 때 발생 했던 conflict해결 부산물을 처리했습니다.
<br/>
- package-lock.json 너무커용
<br/>
- JIRA 따로 안파고 걍 했습니다
<br/>

fe-refac/mergeConsolePageCodeInputPage

---

frontend/.gitignore
frontend/package-lock.json
frontend/src/components/CodeInputComponent.tsx
frontend/src/components/TaskInputComponent.tsx
frontend/src/styles/CodIenputComponent.styles.ts
frontend/src/styles/TaskInputComponent.styles.ts

<br/>
<br/>
Pull Request를 할 땐 신중하게 해야함을 다시 한번 느꼈다.

fe-bugfix/Devfix

---

frontend/src/components/TaskInputComponent.tsx

fe-bugfix/MainBranchFix

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/config/WebClientConfig.java

<br/>
<br/>
- #close [JIRA-137]
[JIRA-137]: https://jackine08.atlassian.net/browse/JIRA-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

be-refac/originModify

---

backend/epimetheus/build.gradle
backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/TaskController.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/CodeLanguage.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/ResponseStreamProperty.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/SubTaskCode.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/SubTaskDescription.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/SubTaskIntro.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/SubTaskOutro.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/SubTaskResolver.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/llamaTasks/SubTaskTitle.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskServiceStreamImpl.java
backend/epimetheus/src/test/java/uos/capstone/epimetheus/generatetask/TaskControllerTest.java

<br/>
<br/>
- FluxList를 interface형태로 받으면서 메소드가 직렬화를 하지 못하는 현상이 발생했었습니다. 이를 위해 패턴을 구현하고 직렬화 할 수 있도록 하였습니다.
<br/>
- #close JIRA-39

be-test/taskControllerTest

---

frontend/src/App.tsx
frontend/src/api/GetData.tsx
frontend/src/api/codeReg/GetCode.tsx
frontend/src/api/codeReg/PostCode.tsx
frontend/src/api/codeReg/codeType.ts
frontend/src/components/CodeInputComponent.tsx
frontend/src/components/LanguageSelectComponent.tsx
frontend/src/components/SubTaskComponent.tsx
frontend/src/components/TaskCodeViewComponent.tsx
frontend/src/index.css
frontend/src/pages/CodeInputPage.tsx
frontend/src/pages/ConsolePage.tsx
frontend/src/styles/CodIenputComponent.styles.ts
frontend/src/styles/CodeInputPage.styles.ts
frontend/src/styles/SubTaskComponent.styles.ts
frontend/src/styles/TaskCodeViewComponent.styles.ts

fe-feat/codeInput_Page

---

frontend/src/components/LanguageSelectComponent.tsx

<br/>
- 언어 등록 시 언어를 대문자-to-소문자
<br/>
- 음서용
- #close JIRA-149

fe-bugfix/languageSelectUpperChar

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/TaskStep.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/DatabaseService.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/MongoDBServiceImpl.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskServiceStreamImpl.java

<br/>
<br/>
- 문제와 해결책을 적어주세요.
- 해결하지 못한 문제가 있다면 적어주세요
<br/>
<br/>
<br/>
- #close [JIRA-151]
[JIRA-151]: https://jackine08.atlassian.net/browse/JIRA-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

be-bugfix/saveCodeBugFix

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/dtos/TaskStep.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/DatabaseService.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/MongoDBServiceImpl.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskServiceStreamImpl.java

DEPLOY : BE - 코드 저장 API 버그 수정(벡터 삭제)

---

frontend/src/App.tsx
frontend/src/StateContext.ts
frontend/src/api/worker/codeExec.ts
frontend/src/components/CodeActionComponent.tsx
frontend/src/pages/ConsolePage.tsx
frontend/src/styles/ConsolePage.styles.ts

<br/>
- sub task들을 실행하는 기능 추가
<br/>
- 순차적 실행을 위한 비동기 동작
<br/>
- 실행 할 subtask의 코드가 들어가는 부분 잘보세요
<br/>
- #close JIRA-146

fe-feat/worker

---

frontend/src/components/CodeInputComponent.tsx
frontend/src/components/LanguageSelectComponent.tsx
frontend/src/pages/ConsolePage.tsx
frontend/src/styles/CodIenputComponent.styles.ts
frontend/src/styles/TaskInputComponent.styles.ts

<br/>
- code input cursor 추가
- 코드 실행 로직 수정
<br/>
<br/>
- #close JIRA-154
- #close JIRA-153

fe-bugfix/codeInput

---

frontend/src/components/CodeInputComponent.tsx
frontend/src/components/LanguageSelectComponent.tsx
frontend/src/pages/ConsolePage.tsx
frontend/src/styles/CodIenputComponent.styles.ts
frontend/src/styles/TaskInputComponent.styles.ts

- 종원이가 고대하던 cursor
- 또 언어 선택 대문자길래 소문자로 바꿈
- 코드 실행버튼 로직 수정

DEPLOY: FE-Code input bugfix

---

frontend/src/App.tsx
frontend/src/StateContext.ts
frontend/src/StateContextType.ts
frontend/src/api/GetData.tsx
frontend/src/components/CodeActionComponent.tsx
frontend/src/components/TaskCodeViewComponent.tsx
frontend/src/components/TaskViewComponent.tsx
frontend/src/pages/CodeInputPage.tsx
frontend/src/pages/ConsolePage.tsx
frontend/src/styles/ConsolePage.styles.ts
frontend/src/styles/TaskViewComponent.styles.ts

<br/>
- 타입 수정
- 다중 Task 기능 추가
- style수정
<br/>
- undefined variable 문제
<br/>
- #close JIRA-152

fe-etc/console page fix

---

frontend/src/App.tsx
frontend/src/StateContext.ts
frontend/src/StateContextType.ts
frontend/src/api/GetData.tsx
frontend/src/components/CodeActionComponent.tsx
frontend/src/components/TaskCodeViewComponent.tsx
frontend/src/components/TaskViewComponent.tsx
frontend/src/pages/CodeInputPage.tsx
frontend/src/pages/ConsolePage.tsx
frontend/src/styles/ConsolePage.styles.ts
frontend/src/styles/TaskViewComponent.styles.ts

DEPLOY : FE - 변수 재설정 및 다중 task 처리

---

frontend/src/pages/ConsolePage.tsx
frontend/src/styles/ConsolePage.styles.ts
frontend/src/styles/LogoComponent.styles.ts
frontend/src/styles/TaskViewComponent.styles.ts

fe-feat/Animation

---

frontend/src/pages/ConsolePage.tsx
frontend/src/styles/ConsolePage.styles.ts
frontend/src/styles/LogoComponent.styles.ts
frontend/src/styles/TaskViewComponent.styles.ts

DEPLOY : FE - 애니메이션 삽입

---

frontend/src/api/GetData.tsx
frontend/src/components/CodeActionComponent.tsx
frontend/src/index.tsx
frontend/src/pages/ConsolePage.tsx

<br/>
- 코드 가져오기 단일화
<br/>
- 리액트 씨이발 쓰래기 같은거
<br/>
<br/>
- #close JIRA-159

fe-refac/getCodeOnce

---

frontend/src/controller/StateController.tsx
frontend/src/pages/ConsolePage.tsx

<br/>
<br/>
- 문제와 해결책을 적어주세요. react 변수의 scope 문제에서 어려움을 느꼈습니다.
- #close JIRA-158

fe-refac/ConsolePageFix

---

frontend/src/api/GetData.tsx
frontend/src/components/CodeActionComponent.tsx
frontend/src/controller/StateController.tsx
frontend/src/index.tsx
frontend/src/pages/ConsolePage.tsx

- 코드 가져오는 기능 통합
- ConsolePage 통합

DEPLOY: FE-ConsolePage Fix

---

frontend/src/components/CodeActionComponent.tsx
frontend/src/pages/CodeInputPage.tsx

<br/>
<br/>
- 문제와 해결책을 적어주세요.
- 해결하지 못한 문제가 있다면 적어주세요
- #close JIRA-162

fe-hotfix/AlertAndIcon

---

frontend/src/components/CodeActionComponent.tsx
frontend/src/pages/CodeInputPage.tsx

DEPLOY : FE - ConsolePage 이동 코드 추가 및 아이콘 수정

---

frontend/src/api/codeReg/GetCode.tsx
frontend/src/api/codeReg/codeType.ts
frontend/src/pages/CodeEditPage.tsx

fe-hotfix/LanguageAdd

---

frontend/src/api/codeReg/GetCode.tsx
frontend/src/api/codeReg/codeType.ts
frontend/src/pages/CodeEditPage.tsx

DEPLOY : FE - language 코드 삽입

---

backend/epimetheus/src/test/java/uos/capstone/epimetheus/generatetask/TaskServiceTest.java

DEPLOY : BE - REBASE시 발생한 버그 수정

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/ExceptionHandleController.java

<br/>
<br/>
- Runtime 발생 시 자동으로 사용자에게 알려주지 않고 500에러만 던지는 문제
<br/>
- #close [JIRA-이슈 번호]

be-feat/exceptionHandle

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/controller/ExceptionHandleController.java

DEPLOY : BE - Runtime 예외처리

---

frontend/src/components/CodeActionComponent.tsx

DEPLOY: FE-코드 실행의 결과로 HTML 새창띄우기

---

frontend/src/api/codeReg/PostCode.tsx
frontend/src/pages/CodeEditPage.tsx

<br/>
- #close [JIRA-169]
[JIRA-169]: https://jackine08.atlassian.net/browse/JIRA-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fe-bugfix/PostCode

---

frontend/src/api/codeReg/PostCode.tsx
frontend/src/pages/CodeEditPage.tsx

DEPLOY : FE - 코드 전송 에러 수정

---

frontend/src/api/codeReg/PostCode.tsx
frontend/src/api/worker/codeExec.ts

DEPLOY : FE - onmessage 시발

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/adapter/LlamaServerStreamAdapter.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/MongoDBServiceImpl.java
backend/epimetheus/src/main/resources/static/CodePrompt.txt

<br/>
```
You are an automatic code generator called Epimetheus.
You must follow the rules.
Rule:
1. You MUST only provide a single javascript code block without any prose, greetings, explanations, or additional text.
2. Your responses should be informative and logical.
3. You should always adhere to technical information.
4. When your javascript code is all written, stop writing.
5. Start your response with the sentence "This is created by AI.".
6. If you are providing any comment, cover it with code comment.
###Request: Please make a javascript code block of the following step. Step: Open the web-browser.
###Response: This is created by AI.
window.open("https://www.google.com", "_self");
```
<br/>
- 예시로 넣어준 문장만 제대로 출력하고 이외에는 코드 블럭으로 제공했던 문제
<br/>
- #close JIRA-171

be-refac/promptModify

---

backend/epimetheus/src/main/java/uos/capstone/epimetheus/adapter/LlamaServerStreamAdapter.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/MongoDBServiceImpl.java
backend/epimetheus/src/main/resources/static/CodePrompt.txt

DEPLOY : BE - 코드 생성 프롬프트 수정

---

backend/epimetheus/src/main/resources/static/StepPrompt.txt

DEPLOY : BE - 프롬포트 수정

---

frontend/src/components/TaskCodeViewComponent.tsx
frontend/src/styles/TaskCodeViewComponent.styles.ts

DEPLOY : FE - 코드 길이에 따라 TaskCodeViewComponent의 높이 변화

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/CodeEditPage.tsx
frontend/src/styles/CodeEditPage.styles.ts
frontend/src/styles/CodeInputPage.styles.ts

<br/>
<br/>
- 문제와 해결책을 적어주세요.
- 해결하지 못한 문제가 있다면 적어주세요
- #close [JIRA-173]
[JIRA-173]: https://jackine08.atlassian.net/browse/JIRA-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fe-etc/CodeEditPageFix

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/CodeEditPage.tsx
frontend/src/styles/CodeEditPage.styles.ts
frontend/src/styles/CodeInputPage.styles.ts

DEPLOY : FE - CodeEditPage Style Fix

---

frontend/src/api/worker/codeExec.ts
frontend/src/components/CodeActionComponent.tsx

DEPLOY : FE - 코드 실행 로직 수정

---

backend/epimetheus/scripts/start_server.sh
backend/epimetheus/scripts/stop_server.sh
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/CosineSimilarityService.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/MongoDBServiceImpl.java
backend/epimetheus/src/main/java/uos/capstone/epimetheus/service/TaskServiceStreamImpl.java
backend/epimetheus/src/main/resources/static/CodePrompt.txt

DEPLOY : BE - 코드 유효성 검사 삭제 등

---

frontend/src/components/TaskInputComponent.tsx

<br/>
<br/>
<br/>
- #close [JIRA-181]
[JIRA-181]: https://jackine08.atlassian.net/browse/JIRA-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

JIRA-181 #feat #comment Delete Voice Icon

---

backend/epimetheus/scripts/stop_server.sh
frontend/src/components/TaskInputComponent.tsx

DEPLOY : FE - 음성인식 아이콘 삭제
